### PR TITLE
Fix bug with init not configuring s3 parameters

### PR DESCRIPTION
**Pull request by lennym**
The bucket name and environment were never set when passed to `init` as parameters due to a broken conditional statement.

Also refactors tests to ensure proper assertions are carried out on the code.

### CODE REVIEW

**Comment by lennym** [comment]
**Important Note: **this should be published as a major version update on account to the changes of behaviour in `init`.

**Comment by nelsonic** [comment]
@lennym agree on the _major_ version update > `6.0.0` ? 
(_at present we are still manually increasing the version in `package.json`_)

**Comment by lennym** [comment]
For certain versions of "manually" - `> npm version major`

**Comment by nelsonic** [comment]
Code looks good. do you want to `npm version major` on your side @lennym ?

**Comment by lennym** [comment]
@nelsonic Once this is merged I'll version and publish it (I'm mildly pedantic about making sure all commits are in before publishing to ensure that the tag that `npm version` creates is an *exact* match of what gets published.)

**Comment by nelsonic** [comment]
got it. merged. 👍

**Comment by lennym** [comment]
Published at v6.0.0

**Pull request merged**
